### ISSUE TITLE
Not working in combination with @prettier/plugin-php

### ISSUE THREAD

**Issue by MichaelvanLaar** [tailwindlabs/prettier-plugin-tailwindcss#149]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.2.7

**What version of Tailwind CSS are you using?**

v3.3.1

**What version of Node.js are you using?**

v18.14.1

**What package manager are you using?**

npm

**What operating system are you using?**

Working remote via SSH. I guess my web hoster uses Debian.

**Reproduction URL**

https://github.com/MichaelvanLaar/bugreport-prettier-plugin-tailwindcss-in-combination-with-plugin-php

**Describe your issue**

When I try to use `prettier-plugin-tailwindcss` in PHP files (in this case, templates files of [Kirby CMS](https://github.com/getkirby)) there seems to be a conflict with `@prettier/plugin-php` – despite using a `.prettierrc` file as described in the documentation.

As long as no PHP tags exist in a PHP file, everything works as it should. But as soon as typical PHP output is present (something like `<?= $page->title() ?>` or any other PHP code) each opening `<` of `<?php` resp `<?=` causes the following error: `Unexpected character "EOF"`

Without `prettier-plugin-tailwindcss` Prettier has no problem with the PHP files.

Tested with the file `/site/templates/default.php` in the reproduction repository.

**Comment by johanguse** [comment]
I'm facing the same issue. I am unable to make it work with PHP (WordPress). I am using this [this boilerplate](https://github.com/blonestar/wp-theme-vite-tailwind)

**Comment by MichaelvanLaar** [comment]
Thank you for the explanation. I know the Prettier PHP plugin has some serious issues when using a mix of PHP and HTML. For the CMS templates I use it is basically unusable because it simply does nothing with the HTML.

My workaround at the time is: Open a new editor in VS Code, set the editor language to HTML and paste in the HTML/PHP mix and then use Prettier. This works most of the time. The PHP stuff is mostly ignored, and the HTML is formatted correctly. Then copy everything back to the original file.

Not a very good solution, but at least it works.

I guess I will do the same with the Tailwind CSS classes: Create an HTML document with minimal markup, but in the project, so that Prettier uses the sorting plugin. And then just copy the classes string I’m working on from the PHP file to the HTML file, sort it there, and copy it back to its original location.

**Comment by vanbasx** [comment]
Hello, you can install vscode plugin [Headwind](https://marketplace.visualstudio.com/items?itemName=heybourn.headwind)

**Comment by sboerrigter** [comment]
I have a different workaround solution for this that might be helpful to others as well:

1. I renamed all my PHP template files and components from `[filename].php` to `[filename].phtml`.

2. I configured Prettier to format PHTML files as HTML files by adding this to my prettier config:

```
"overrides": [
  {
    "files": "*.phtml",
    "options": {
      "parser": "html"
    }
  }
]
```

3. I added some `<!-- prettier-ignore -->` tags here and there to prevent prettier from screwing up the PHP formatting.

This way, the HTML is formatted by Prettier and the Tailwind classes are sorted. I only have to take care of the formatting of a few PHP tags in my template files. That isn't a big issue, because most of the complexer logic is in other files with the `.php` extension, which are handled by `@prettier/plugin-php`.
