### ISSUE TITLE
This plugin breaks Storybook initialisation step when prettier3.0.0 is in package.json

### ISSUE THREAD

**Issue by Seefer** [tailwindlabs/prettier-plugin-tailwindcss#188]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.4.1

**What version of Tailwind CSS are you using?**

3.3.3

**What version of Node.js are you using?**

18.16.1

**What package manager are you using?**

Pnpm

**What operating system are you using?**

Windows 11

**Reproduction URL**
https://github.com/Seefer/my-app

**Describe your issue**

Having issues installing and initializing Storybook if this plugin is installed and manually loaded in`.prettierrc` config file. This issue is also discussed on Storybook Github issue #23465 page at https://github.com/storybookjs/storybook/issues/23465
1. Git clone above public repo
2. `cd` into `my-app` and run `pnpm i` to install all packages

This repo is a Next.js project with all defaults accepted and `prettier` and `prettier-plugin-tailwindcss` installed using `pnpm add -D prettier prettier-plugin-tailwindcss`

2. cd into my-app and run `pnpm dlx storybook@latest init`

Package install will fail during `Installing Storybook Dependencies` with the error shown in the screenshot.

3. Delete `my-app` folder and git clone the above repo again
4. `cd` into my-app and run `pnpm i` to install packages.
5. run `pnpm uninstall prettier-plugin-tailwindcss` to remove the plugin
6. Delete `.prettierrc` from root directory
7. Run `pnpm dlx storybook@latest init` and everything will install and initialize without error.

Note in the screenshot error logs that prettier2.8.8 is being referenced in `.pnpm` folder in `node_mobules`. I believe this is Pnpm's virtual package store, presumably using filesystem hard linking to link to local packages on local storage. Also note that `prettier2.8.8` and `prettier3.0.0` are in there but `package.json` only contains prettier3.0.0.

I'm a web dev newcomer but am I to assume this plugin will only work if I revert to prettier2.8.8? If so then the Installation instructions for this repo README.MD may need to be adjusted to explicitly install `prettier@2.8.8`?

![image](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/129484/fbbd88d8-aaa3-4ac2-b22d-3ee3e0fcfcee)

**Comment by thecrypticace** [comment]
Hey — after a bit of finessing of the deps and installation I got pnpm to give me a tree that included storybook:

<img width="365" alt="Screenshot 2023-07-26 at 15 24 16" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/614993/5151b0c4-d519-4b66-88d5-be8896967ed5">


Storybook isn't compatible with Prettier v3 and I'm guessing since the story book dependency installation is a separate step pnpm doesn't know at initial installation time that it shouldn't install Prettier v3. And since our plugin is compatible with both it opts to install the latest version.

You can work around this by explicitly adding Prettier 2.8 to the root of your own project:
```
pnpm add prettier@2.8
```

Once you do that you can install and launch storybook as expected:

<img width="644" alt="Screenshot 2023-07-26 at 15 28 47" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/614993/b78062b4-8779-41a5-9fcb-dc93c0b718e9">

Hope that helps! ✨
