### ISSUE TITLE
Plugin is evaluating theme and placing output into files

### ISSUE THREAD

**Issue by SalTor** [tailwindlabs/prettier-plugin-tailwindcss#193]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.4.1

**What version of Tailwind CSS are you using?**

v3.3.3

**What version of Node.js are you using?**

v20.5.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/SalTor/prettier-tailwind-plugin-reproduction-repo

**Describe your issue**

1. Look at the contents of `themes/our-theme.ts` and notice there's a few console logs in there
2. Run `npx prettier themes/our-theme.ts` and notice the evaluation of those console logs get prepended to the top of the output

I noticed this from my editor running prettier before save and verified the prettier CLI also yields the same result

Replacing this plugin with a different one does not yield the same experience

I originally installed this plugin so I could get class names sorted to satisfy the eslint plugin warnings but I've since realized I can use the eslint tailwind plugin and run "eslint fix all" to get the same effect but I thought this was wild enough of a result to at least surface to the tailwindlabs team

**Comment by thecrypticace** [comment]
Hey — this is happening because you are including the file with `console.log` statements in your Tailwind config file — which is JS / TS and must be run/required to build the configuration. This executes the JS in that file and all required/imported files.

<img width="533" alt="Screenshot 2023-07-24 at 11 11 29" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/614993/760b8320-c0c4-49ed-9fea-e0d73f0c39a0">

This output, however, is only in the terminal. It doesn't affect what is written to files when using Prettier's `-w` flag to save the newly formatted file (e.g. `npx prettier themes/our-theme.ts -w`):

<img width="577" alt="Screenshot 2023-07-24 at 11 09 09" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/614993/06a9364e-719f-4795-b1f0-37c589bcd891">

As such this is considered not to be a bug given that it does not affect the actual result of formatting files. The only "change" here could be to override console.log but you can workaround that by using something like `process.stdout.write()`.

Hope that helps! ✨

**Comment by SalTor** [comment]
Interesting yes I do see that with the `-w` flag it doesn't write to the file. Maybe I'll investigate how my editor is running prettier then because I have been getting this output prepended to the top of the file. And logging in the theme file is also not something I'd actually do but I thought it was a peculiar behavior anyway--again, I don't think my editor(s) (emacs/neovim) uses the -w flag and maybe it should be
