### ISSUE TITLE
Outdated use of require() causing errors in external library usage

### ISSUE THREAD

**Issue by martitv** [tailwindlabs/prettier-plugin-tailwindcss#214]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.4

**What version of Tailwind CSS are you using?**

v3.3.3

**What version of Node.js are you using?**

v18.16.1

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Reproduction URL**

None

**Describe your issue**

I am trying to use [ts-to-zod](https://github.com/fabien0102/ts-to-zod) to generate Zod schemas from my autogenerated types. ts-to-zod fails due to:
```
Error: require() of ES Module C:\Users\Myself\Repositories\MyRepo\myApp\node_modules\.pnpm\prettier-plugin-tailwindcss@0.5.4_prettier@3.0.3\node_modules\prettier-plugin-tailwindcss\dist\index.mjs not supported.
Instead change the require of C:\Users\Myself\Repositories\MyRepo\myApp\node_modules\.pnpm\prettier-plugin-tailwindcss@0.5.4_prettier@3.0.3\node_modules\prettier-plugin-tailwindcss\dist\index.mjs to a dynamic import() which is available in all CommonJS modules.
    Code: ERR_REQUIRE_ESM
```

**Comment by thecrypticace** [comment]
@martitv this error is generally because one is using `require()` to load the plugin when they should not be. Looking at the linked issue I suspect it's trying to use Prettier 2 to load this plugin when it is Prettier 3 only.

Can you provide a reproduction repo I can take a look at (doesn't need to be minimal — just want to verify things to see if I'm on the right track about this).

**Comment by martitv** [comment]
Here: https://github.com/martitv/ts-to-zod-prettier-plugin-tailwindcss

Just stand in the "my-app" folder and run `npm run codegen:schemas` and you should see the error

**Comment by martitv** [comment]
Thanks for the help! Ill reopen the issue on ts-to-zod to tell the to update their prettier version
