### ISSUE TITLE
Adding this plugin, errors out prettier

### ISSUE THREAD

**Issue by pvinis** [tailwindlabs/prettier-plugin-tailwindcss#309]
**What version of `prettier-plugin-tailwindcss` are you using?**
v0.6.5 and i tried v0.6.0 too. both same issue.

**What version of Tailwind CSS are you using?**
v3.4.7 and i tried v3.3.0 too. same issue.

**What version of Node.js are you using?**
v20.16.0

**What package manager are you using?**
pnpm v9.6.0

**What operating system are you using?**
macos

**Reproduction URL**

https://github.com/pvinis/repro-prettier-tailwind-plugin

**Describe your issue**

When trying to run prettier in vscode or terminal (with pnpx prettier src/somefile.tsx), I get:
```
src/ds/Screen.tsx
[error] src/ds/Screen.tsx: SyntaxError: Unexpected token, expected "{" (14:8)
[error]    1 | import { PropsWithChildren } from "react"
[error]    2 | import { View, ViewStyle } from "react-native"
[error]    3 | import { useSafeAreaInsets } from "react-native-safe-area-context"
[error]    4 | import { tws } from "@/twHelpers"
[error]    5 |
[error]    6 | export interface ScreenProps {
[error]    7 | 	style?: ViewStyle
[error]    8 | }
[error]    9 |
[error]   10 | export function Screen({ children, style }: PropsWithChildren<ScreenProps>) {
[error]   11 | 	const saInsets = useSafeAreaInsets()
[error]   12 |
[error]   13 | 	return (
[error]   14 | 		<View style={tws("flex flex-1 bg-black", style)}>
[error]   15 | 			<View style={tws("flex flex-1", { marginTop: saInsets.top })}>{children}</View>
[error]   16 | 		</View>
[error]   17 | 	)
[error]   18 | }
```

**Comment by thecrypticace** [comment]
Hi! So this is happening because you're including `twrnc` in your tailwind config file. `twrnc` imports `react-native` which is written in Flow which eventually results in these errors occurring.

[This line](https://github.com/pvinis/repro-prettier-tailwind-plugin/blob/main/tailwind.config.js#L1) in your repro is the cause of the error.

To fix this, instead of importing `plugin` from `twrnc`:
```js
const { plugin } = require("twrnc")
```

You should instead import it from `tailwindcss/plugin`:
```js
const plugin = require("tailwindcss/plugin")
```

Hope that helps!

**Comment by pvinis** [comment]
wow! I will try it that way, thank you! I appreciate your time!
