### ISSUE TITLE
Not working on HTML within .php files

### ISSUE THREAD

**Issue by dmmihaylov** [tailwindlabs/prettier-plugin-tailwindcss#52]
Hey guys,

I installed the plugin and it's working like a charm on .html files (VSCode, Prettier extension + prettier php plugin).

However, doesn't seem to apply the same changes if file's extension is .php.

Am I missing something or currently HTML in PHP files is not supported?

**Comment by maltesa** [comment]
It would be great to be able to specify file extensions/types where classes should be sorted. I would like to use it in `.html.erb` files.

**Comment by bkno** [comment]
I also couldn't get it to work in .php files using the same VSCode setup.

Haven't really used prettier before much, but I don't think it can cope with formatting HTML in a PHP file either. When I installed the PHP plugin it just sorted the PHP parts of the file, not the HTML. Just noting in case it is related.

**Comment by RichForever** [comment]
Its major feature for me (wp developer) and its not working. So bad, hope it will be added soon

**Comment by DanielGSoftware** [comment]
Not working for me either with PHPStorm

**Comment by bradlc** [comment]
Hey @dmmihaylov. `prettier-plugin-tailwindcss` does not sort classes in PHP files because Prettier itself (with `@prettier/plugin-php`) [does not format HTML in PHP files](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHh6ANwACTZjZMewAXgAdEE2jzfWAPnWDzGuzzaWAejXz6+ulgH5jMFfMNghXJIAfX8YAAFFJBJgYhhMKCACR-ZQARiYCIgymyAEp1sIoOtQes4as-ijCcSINl1tjgLcztAYIIIJhCYikQBqNEYh7w8kc8lYgDc1066z+ANBRxivjAagAHkc9i8QFKKFAjkwjgB3XrUBUvZlnCFQmGg6n0xnMo7EKU4eDjKAkI4C9rXDUgKT9fxwFR6q3YdVXEDUP4UU6KwN9ANHfzEdjEPXhKCYzFCm6YEDtIA).

**Comment by Finallf** [comment]
It appears to have been fixed:
#https://github.com/shufo/prettier-plugin-blade/issues/161#issuecomment-1399220191

Would there be a way to fix the official one too?
