### ISSUE TITLE
Unit test fail

### ISSUE THREAD

**Issue by ShroXd** [tailwindlabs/prettier-plugin-tailwindcss#63]
**What version of `prettier-plugin-tailwindcss` are you using?**

For example: v0.1.8

**What version of Tailwind CSS are you using?**
None

**What version of Node.js are you using?**

v14.17.5

**What package manager are you using?**

pnpm, npm

**What operating system are you using?**

macOS

**Reproduction URL**

This repo

**Describe your issue**

I tried to run the unit test of this repo, but the test case for svelte is fail. Look like it's because we can't import the svelte/compiler, but I don't know how to address this problem.

![image](https://user-images.githubusercontent.com/48713853/155663143-66d13887-7720-4a1d-8a6e-8bd3df944967.png)

**Comment by bradlc** [comment]
This is likely because you're using a package manager that doesn't [auto-install peer dependencies](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#:~:text=install%20%2D%2Dno%2Dsave.-,Peer%20dependencies,-Automatically%20installing%20peer). Either way this should be fine now, as of ec412a2cbde5df1075f036f0c21b5308a66ea567 👍

**Comment by fabien** [comment]
For whatever reason, I wasn't able to get this working without explicitly running `npm install svelte` in my app (that is only formatting framework code, including Svelte components, but it's not actually a Svelte based app). This is with NPM v.7. I got the same error as above.
