### ISSUE TITLE
Transform/translate property with old tailwind (1.9.6)

### ISSUE THREAD

**Issue by Yanduz** [tailwindlabs/prettier-plugin-tailwindcss#75]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.1.10

**What version of Tailwind CSS are you using?**

v1.9.6

**What version of Node.js are you using?**

v17.9.0

**What package manager are you using?**

Yarn

**What operating system are you using?**

macOS

**Describe your issue**

Our team is using the old version of tailwind 1.9.6.
I ran into a problem that in the old version the translate property declaration should be paired with transform, but the sort plugin doesn't take this into account and overwrites the property. Is there a way to fix this? Thank you!

<img width="542" alt="image" src="https://user-images.githubusercontent.com/27006337/167873701-239c4deb-0e01-4aa9-b9d7-8cbb72fc1cb6.png">
<img width="378" alt="image" src="https://user-images.githubusercontent.com/27006337/167874776-8ea6d37b-fd2a-4b69-a383-950331534347.png">
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/27006337/167875411-13052ead-a515-4b00-848c-7bfa541d624c.png">
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/27006337/167875652-30253695-3f6e-452d-a740-b4464bef9276.png">

**Comment by adamwathan** [comment]
Hey! As mentioned in the readme, the Prettier plugin is only compatible with v3 and up. It’s “working” in v1 because installing the Prettier plugin will install v3 as a dependency but you’ll get problems like you’re seeing because apply behaved differently in v1 so it’s not safe to sort those classes.

Nothing we can really do here I’m afraid as we have no plans to support older versions. Would encourage you to upgrade your project instead 👍🏻

**Comment by meirroth** [comment]
To anyone having this issue, here's how I solved it:
Separate the `transform` onto a line before any other modifiers, like this:
![image](https://user-images.githubusercontent.com/12494197/214875815-5fa21b4a-856f-4851-a716-5a1fe5006d15.png)
