### ISSUE TITLE
Plugin giving error after following blog post

### ISSUE THREAD

**Issue by ryanbrwr** [tailwindlabs/prettier-plugin-tailwindcss#8]
Hey all, excited about using this plugin in all of my projects. I was trying to get it set up, but keep getting this error. Any help would be appreciated! 
![image](https://user-images.githubusercontent.com/34748418/150905013-3d80d41e-b84f-4390-8899-d8623e2a0c24.png)

**Comment by JavierMartinz** [comment]
I'm also getting this error in a yarn monorepo setup with 2 NextJS apps.

**Comment by bradlc** [comment]
Hey @ryanbrwr. It looks like you're using [`prettier-plugin-tailwind`](https://www.npmjs.com/package/prettier-plugin-tailwind), not [`prettier-plugin-tailwindcss`](https://www.npmjs.com/package/prettier-plugin-tailwindcss)

**Comment by ryanbrwr** [comment]
yeah unfortunately I am using prettier-plugin-tailwindcss and this is not the issue. I followed the blogpost exactly as it was written. Any other suggestions?

**Comment by reinink** [comment]
@ryanbrwr Hey, are you sure? In the error message above I see a reference to the [tailwind-classes-sorter](https://www.npmjs.com/package/tailwind-classes-sorter) package and the [prettier-plugin-tailwind](https://www.npmjs.com/package/prettier-plugin-tailwind) package. Neither of these packages are managed by us.

<img width="309" alt="Screen Shot 2022-01-25 at 9 07 18 AM" src="https://user-images.githubusercontent.com/882133/150992282-c16c6855-a731-4086-9630-55aaf68e2949.png">

Even if you have our package (`prettier-plugin-tailwindcss`) installed, you could still be getting errors because of these other packages.

**Comment by ryanbrwr** [comment]
Ahhhh okay it seems at some point I installed prettier-plugin-tailwind prior to switching to this package, appreciate the help!

**Comment by reinink** [comment]
@ryanbrwr My pleasure! 💪
